# Generated by Django 6.0.5 on 2026-05-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_usuario_tarefa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
    ]
