# Generated by Django 6.0.5 on 2026-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_fornecedor_produto_entrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='preco_custo',
            new_name='preco_custo_unitario',
        ),
        migrations.AddField(
            model_name='entrada',
            name='nfe',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
