# Generated by Django 6.0.5 on 2026-05-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_rename_preco_custo_entrada_preco_custo_unitario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
